"""added relationships between User and File

Revision ID: 4e76d306c5b7
Revises: 4f0c95d90bc3
Create Date: 2023-05-30 20:22:31.011791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e76d306c5b7'
down_revision = '4f0c95d90bc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'file', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'owner_id')
    # ### end Alembic commands ###
