"""added unique constraint to file_url

Revision ID: 61b86dffbc95
Revises: bb6cbc280cf9
Create Date: 2023-06-01 16:47:53.894273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b86dffbc95'
down_revision = 'bb6cbc280cf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'media', ['file_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='unique')
    # ### end Alembic commands ###
